// The ShortURL service definition.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/short_url.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShortURLCreateRequest - запрос на создание короткой ссылки
type ShortURLCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ShortURLCreateRequest) Reset() {
	*x = ShortURLCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLCreateRequest) ProtoMessage() {}

func (x *ShortURLCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLCreateRequest.ProtoReflect.Descriptor instead.
func (*ShortURLCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURLCreateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ShortURLCreateResponse - ответ на запрос на создание короткой ссылки
type ShortURLCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ShortURLCreateResponse) Reset() {
	*x = ShortURLCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLCreateResponse) ProtoMessage() {}

func (x *ShortURLCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLCreateResponse.ProtoReflect.Descriptor instead.
func (*ShortURLCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURLCreateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// ShortURLCreateBatchRequest - запрос на массовое создание коротких ссылок
type ShortURLCreateBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShortURLCreateBatchRequest_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ShortURLCreateBatchRequest) Reset() {
	*x = ShortURLCreateBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLCreateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLCreateBatchRequest) ProtoMessage() {}

func (x *ShortURLCreateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLCreateBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortURLCreateBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{2}
}

func (x *ShortURLCreateBatchRequest) GetItems() []*ShortURLCreateBatchRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// ShortURLCreateBatchResponse - ответ на запрос на массовое создание коротких ссылок
type ShortURLCreateBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShortURLCreateBatchResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ShortURLCreateBatchResponse) Reset() {
	*x = ShortURLCreateBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLCreateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLCreateBatchResponse) ProtoMessage() {}

func (x *ShortURLCreateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLCreateBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortURLCreateBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{3}
}

func (x *ShortURLCreateBatchResponse) GetItems() []*ShortURLCreateBatchResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// ShortURLDeleteBatchRequest - запрос на массовое удаление коротких ссылок
type ShortURLDeleteBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ShortURLDeleteBatchRequest) Reset() {
	*x = ShortURLDeleteBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLDeleteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLDeleteBatchRequest) ProtoMessage() {}

func (x *ShortURLDeleteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLDeleteBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortURLDeleteBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{4}
}

func (x *ShortURLDeleteBatchRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// ShortURLDeleteBatchResponse - ответ на запрос на массовое удаление коротких ссылок
type ShortURLDeleteBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShortURLDeleteBatchResponse) Reset() {
	*x = ShortURLDeleteBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLDeleteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLDeleteBatchResponse) ProtoMessage() {}

func (x *ShortURLDeleteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLDeleteBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortURLDeleteBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{5}
}

// ShortURLGetByUserIDRequest - запрос на получение списка коротких ссылок текущего пользователя
type ShortURLGetByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShortURLGetByUserIDRequest) Reset() {
	*x = ShortURLGetByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLGetByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLGetByUserIDRequest) ProtoMessage() {}

func (x *ShortURLGetByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLGetByUserIDRequest.ProtoReflect.Descriptor instead.
func (*ShortURLGetByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{6}
}

// ShortURLGetByUserIDResponse - ответ на запрос на получение списка коротких ссылок текущего пользователя
type ShortURLGetByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShortURLGetByUserIDResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ShortURLGetByUserIDResponse) Reset() {
	*x = ShortURLGetByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLGetByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLGetByUserIDResponse) ProtoMessage() {}

func (x *ShortURLGetByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLGetByUserIDResponse.ProtoReflect.Descriptor instead.
func (*ShortURLGetByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{7}
}

func (x *ShortURLGetByUserIDResponse) GetItems() []*ShortURLGetByUserIDResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShortURLCreateBatchRequest_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *ShortURLCreateBatchRequest_Item) Reset() {
	*x = ShortURLCreateBatchRequest_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLCreateBatchRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLCreateBatchRequest_Item) ProtoMessage() {}

func (x *ShortURLCreateBatchRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLCreateBatchRequest_Item.ProtoReflect.Descriptor instead.
func (*ShortURLCreateBatchRequest_Item) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ShortURLCreateBatchRequest_Item) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortURLCreateBatchRequest_Item) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortURLCreateBatchResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortURLCreateBatchResponse_Item) Reset() {
	*x = ShortURLCreateBatchResponse_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLCreateBatchResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLCreateBatchResponse_Item) ProtoMessage() {}

func (x *ShortURLCreateBatchResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLCreateBatchResponse_Item.ProtoReflect.Descriptor instead.
func (*ShortURLCreateBatchResponse_Item) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ShortURLCreateBatchResponse_Item) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortURLCreateBatchResponse_Item) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortURLGetByUserIDResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl    string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortURLGetByUserIDResponse_Item) Reset() {
	*x = ShortURLGetByUserIDResponse_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_short_url_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLGetByUserIDResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLGetByUserIDResponse_Item) ProtoMessage() {}

func (x *ShortURLGetByUserIDResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_short_url_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLGetByUserIDResponse_Item.ProtoReflect.Descriptor instead.
func (*ShortURLGetByUserIDResponse_Item) Descriptor() ([]byte, []int) {
	return file_api_short_url_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ShortURLGetByUserIDResponse_Item) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ShortURLGetByUserIDResponse_Item) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

var File_api_short_url_proto protoreflect.FileDescriptor

var file_api_short_url_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x15,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x30, 0x0a, 0x16, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x52, 0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xac, 0x01, 0x0a, 0x1a, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x50, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0xa8, 0x01, 0x0a, 0x1b, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x52, 0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x4a, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x22, 0x32, 0x0a, 0x1a, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x52, 0x4c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x52, 0x4c, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x1b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x52, 0x4c, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x1a, 0x46, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x32, 0xdb, 0x02, 0x0a, 0x08,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x47, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x52, 0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x56, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x52, 0x4c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x56, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x52, 0x4c, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_short_url_proto_rawDescOnce sync.Once
	file_api_short_url_proto_rawDescData = file_api_short_url_proto_rawDesc
)

func file_api_short_url_proto_rawDescGZIP() []byte {
	file_api_short_url_proto_rawDescOnce.Do(func() {
		file_api_short_url_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_short_url_proto_rawDescData)
	})
	return file_api_short_url_proto_rawDescData
}

var file_api_short_url_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_short_url_proto_goTypes = []interface{}{
	(*ShortURLCreateRequest)(nil),            // 0: proto.ShortURLCreateRequest
	(*ShortURLCreateResponse)(nil),           // 1: proto.ShortURLCreateResponse
	(*ShortURLCreateBatchRequest)(nil),       // 2: proto.ShortURLCreateBatchRequest
	(*ShortURLCreateBatchResponse)(nil),      // 3: proto.ShortURLCreateBatchResponse
	(*ShortURLDeleteBatchRequest)(nil),       // 4: proto.ShortURLDeleteBatchRequest
	(*ShortURLDeleteBatchResponse)(nil),      // 5: proto.ShortURLDeleteBatchResponse
	(*ShortURLGetByUserIDRequest)(nil),       // 6: proto.ShortURLGetByUserIDRequest
	(*ShortURLGetByUserIDResponse)(nil),      // 7: proto.ShortURLGetByUserIDResponse
	(*ShortURLCreateBatchRequest_Item)(nil),  // 8: proto.ShortURLCreateBatchRequest.Item
	(*ShortURLCreateBatchResponse_Item)(nil), // 9: proto.ShortURLCreateBatchResponse.Item
	(*ShortURLGetByUserIDResponse_Item)(nil), // 10: proto.ShortURLGetByUserIDResponse.Item
}
var file_api_short_url_proto_depIdxs = []int32{
	8,  // 0: proto.ShortURLCreateBatchRequest.items:type_name -> proto.ShortURLCreateBatchRequest.Item
	9,  // 1: proto.ShortURLCreateBatchResponse.items:type_name -> proto.ShortURLCreateBatchResponse.Item
	10, // 2: proto.ShortURLGetByUserIDResponse.items:type_name -> proto.ShortURLGetByUserIDResponse.Item
	0,  // 3: proto.ShortURL.Create:input_type -> proto.ShortURLCreateRequest
	2,  // 4: proto.ShortURL.CreateBatch:input_type -> proto.ShortURLCreateBatchRequest
	4,  // 5: proto.ShortURL.DeleteBatch:input_type -> proto.ShortURLDeleteBatchRequest
	6,  // 6: proto.ShortURL.GetByUserID:input_type -> proto.ShortURLGetByUserIDRequest
	1,  // 7: proto.ShortURL.Create:output_type -> proto.ShortURLCreateResponse
	3,  // 8: proto.ShortURL.CreateBatch:output_type -> proto.ShortURLCreateBatchResponse
	5,  // 9: proto.ShortURL.DeleteBatch:output_type -> proto.ShortURLDeleteBatchResponse
	7,  // 10: proto.ShortURL.GetByUserID:output_type -> proto.ShortURLGetByUserIDResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_short_url_proto_init() }
func file_api_short_url_proto_init() {
	if File_api_short_url_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_short_url_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLCreateBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLCreateBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLDeleteBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLDeleteBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLGetByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLGetByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLCreateBatchRequest_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLCreateBatchResponse_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_short_url_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLGetByUserIDResponse_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_short_url_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_short_url_proto_goTypes,
		DependencyIndexes: file_api_short_url_proto_depIdxs,
		MessageInfos:      file_api_short_url_proto_msgTypes,
	}.Build()
	File_api_short_url_proto = out.File
	file_api_short_url_proto_rawDesc = nil
	file_api_short_url_proto_goTypes = nil
	file_api_short_url_proto_depIdxs = nil
}
