// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/short_url.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShortURLClient is the client API for ShortURL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortURLClient interface {
	Create(ctx context.Context, in *ShortURLCreateRequest, opts ...grpc.CallOption) (*ShortURLCreateResponse, error)
	CreateBatch(ctx context.Context, in *ShortURLCreateBatchRequest, opts ...grpc.CallOption) (*ShortURLCreateBatchResponse, error)
	DeleteBatch(ctx context.Context, in *ShortURLDeleteBatchRequest, opts ...grpc.CallOption) (*ShortURLDeleteBatchResponse, error)
	GetByUserID(ctx context.Context, in *ShortURLGetByUserIDRequest, opts ...grpc.CallOption) (*ShortURLGetByUserIDResponse, error)
}

type shortURLClient struct {
	cc grpc.ClientConnInterface
}

func NewShortURLClient(cc grpc.ClientConnInterface) ShortURLClient {
	return &shortURLClient{cc}
}

func (c *shortURLClient) Create(ctx context.Context, in *ShortURLCreateRequest, opts ...grpc.CallOption) (*ShortURLCreateResponse, error) {
	out := new(ShortURLCreateResponse)
	err := c.cc.Invoke(ctx, "/proto.ShortURL/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortURLClient) CreateBatch(ctx context.Context, in *ShortURLCreateBatchRequest, opts ...grpc.CallOption) (*ShortURLCreateBatchResponse, error) {
	out := new(ShortURLCreateBatchResponse)
	err := c.cc.Invoke(ctx, "/proto.ShortURL/CreateBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortURLClient) DeleteBatch(ctx context.Context, in *ShortURLDeleteBatchRequest, opts ...grpc.CallOption) (*ShortURLDeleteBatchResponse, error) {
	out := new(ShortURLDeleteBatchResponse)
	err := c.cc.Invoke(ctx, "/proto.ShortURL/DeleteBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortURLClient) GetByUserID(ctx context.Context, in *ShortURLGetByUserIDRequest, opts ...grpc.CallOption) (*ShortURLGetByUserIDResponse, error) {
	out := new(ShortURLGetByUserIDResponse)
	err := c.cc.Invoke(ctx, "/proto.ShortURL/GetByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortURLServer is the server API for ShortURL service.
// All implementations must embed UnimplementedShortURLServer
// for forward compatibility
type ShortURLServer interface {
	Create(context.Context, *ShortURLCreateRequest) (*ShortURLCreateResponse, error)
	CreateBatch(context.Context, *ShortURLCreateBatchRequest) (*ShortURLCreateBatchResponse, error)
	DeleteBatch(context.Context, *ShortURLDeleteBatchRequest) (*ShortURLDeleteBatchResponse, error)
	GetByUserID(context.Context, *ShortURLGetByUserIDRequest) (*ShortURLGetByUserIDResponse, error)
	mustEmbedUnimplementedShortURLServer()
}

// UnimplementedShortURLServer must be embedded to have forward compatible implementations.
type UnimplementedShortURLServer struct {
}

func (UnimplementedShortURLServer) Create(context.Context, *ShortURLCreateRequest) (*ShortURLCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedShortURLServer) CreateBatch(context.Context, *ShortURLCreateBatchRequest) (*ShortURLCreateBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBatch not implemented")
}
func (UnimplementedShortURLServer) DeleteBatch(context.Context, *ShortURLDeleteBatchRequest) (*ShortURLDeleteBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBatch not implemented")
}
func (UnimplementedShortURLServer) GetByUserID(context.Context, *ShortURLGetByUserIDRequest) (*ShortURLGetByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserID not implemented")
}
func (UnimplementedShortURLServer) mustEmbedUnimplementedShortURLServer() {}

// UnsafeShortURLServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortURLServer will
// result in compilation errors.
type UnsafeShortURLServer interface {
	mustEmbedUnimplementedShortURLServer()
}

func RegisterShortURLServer(s grpc.ServiceRegistrar, srv ShortURLServer) {
	s.RegisterService(&ShortURL_ServiceDesc, srv)
}

func _ShortURL_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURLCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortURLServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShortURL/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortURLServer).Create(ctx, req.(*ShortURLCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortURL_CreateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURLCreateBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortURLServer).CreateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShortURL/CreateBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortURLServer).CreateBatch(ctx, req.(*ShortURLCreateBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortURL_DeleteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURLDeleteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortURLServer).DeleteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShortURL/DeleteBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortURLServer).DeleteBatch(ctx, req.(*ShortURLDeleteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortURL_GetByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURLGetByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortURLServer).GetByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShortURL/GetByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortURLServer).GetByUserID(ctx, req.(*ShortURLGetByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortURL_ServiceDesc is the grpc.ServiceDesc for ShortURL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortURL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShortURL",
	HandlerType: (*ShortURLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ShortURL_Create_Handler,
		},
		{
			MethodName: "CreateBatch",
			Handler:    _ShortURL_CreateBatch_Handler,
		},
		{
			MethodName: "DeleteBatch",
			Handler:    _ShortURL_DeleteBatch_Handler,
		},
		{
			MethodName: "GetByUserID",
			Handler:    _ShortURL_GetByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/short_url.proto",
}
